version: '3'

services:
    fabriquedemo-db:
        container_name: fabriquedemo-db
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=app-demo
            - MYSQL_PASSWORD=root
        ports:
            - "3307:3306"

    swagger:
        container_name: fabriquedemo-swagger-ui
        image: swaggerapi/swagger-ui:v3.23.3
        environment:
            - API_URL=api-doc/swagger/fabrique/swagger.yml
        ports:
            - "9002:8080"
        volumes:
            - ./api-doc:/usr/share/nginx/html/api-doc
volumes:
    fabriquedemo-db: