openapi: 3.0.1

info:
  title: 'api'
  description: 'api'
  version: '1.0.0'

paths:
  /:
    get:
      operationId: getQuestionList
      description: 'Get question list'
      tags:
        - Question

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'components.yml#/components/schemas/Question'

    post:
      operationId: createQuestion
      description: 'Create new question'
      tags:
        - Question
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateQuestionRequest'
      responses:
        200:
          description: OK
        400:
          description: Error

components:
  schemas:
    CreateQuestionRequest:
      type: object
      properties:
        text:
          type: string
          example: 'What is it..?'
        type:
          type: string
          example: SINGLE_ANSWER
          enum:
            - SINGLE_ANSWER