openapi: 3.0.1

info:
    title: 'api'
    description: 'api'
    version: '1.0.0'

paths:
    /:
        post:
            operationId: userAuth
            description: 'User auth'
            tags:
                - User
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/AuthRequest'
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/AuthResponse'
                401:
                    description: Error
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    code:
                                        description: Код ошибки
                                        type: string
                                        enum:
                                            - unauthorized
                                            - interaction_error
                                    type:
                                        type: string
                                        example: 'auth'
                                    message:
                                        description: Сообщение об ошибке
                                        type: string
                                        example: 'Error message'

components:
    schemas:
        AuthRequest:
            type: object
            properties:
                login:
                    type: string
                    example: 'login'
                password:
                    type: string
                    example: 'pass'

        AuthResponse:
            type: object
            properties:
                redirectUrl:
                    type: string
                    example: 'poker://on-login?auth=B6CAB88D07D92C821DE48FEB8047CE16'
